# Autogenerated wrapper script for GPI2_jll for powerpc64le-linux-gnu
export gaspi_cleanup, gaspi_logger, gaspi_run, libGPI2, libGPI2_dbg, libGPI2_stats, ssh_spawner

JLLWrappers.@generate_wrapper_header("GPI2")
JLLWrappers.@declare_file_product(gaspi_cleanup)
JLLWrappers.@declare_file_product(gaspi_run)
JLLWrappers.@declare_library_product(libGPI2, "libGPI2.so.0")
JLLWrappers.@declare_library_product(libGPI2_dbg, "libGPI2-dbg.so.0")
JLLWrappers.@declare_library_product(libGPI2_stats, "libGPI2-stats.so.0")
JLLWrappers.@declare_executable_product(gaspi_logger)
JLLWrappers.@declare_file_product(ssh_spawner)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_file_product(
        gaspi_cleanup,
        "bin/gaspi_cleanup",
    )

    JLLWrappers.@init_file_product(
        gaspi_run,
        "bin/gaspi_run",
    )

    JLLWrappers.@init_library_product(
        libGPI2,
        "lib64/libGPI2.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libGPI2_dbg,
        "lib64/libGPI2-dbg.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libGPI2_stats,
        "lib64/libGPI2-stats.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        gaspi_logger,
        "bin/gaspi_logger",
    )

    JLLWrappers.@init_file_product(
        ssh_spawner,
        "bin/ssh.spawner",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
